/**
 * Customer rebalancing recommendations — list / accept / dismiss (E8-S4;
 * api-contracts.md §10.1-10.3). Recommendations are generated by
 * advance-a-day, not by this module; accepting/dismissing only records
 * intent (no brokerage integration).
 */
import { apiRequest } from './client';

export type ProposedActionType = 'BUY' | 'SELL';

export interface ProposedAction {
  asset_class_id: number;
  asset_class_code: string;
  action: ProposedActionType;
  /** Money, 2 decimals, verbatim from the API — never re-formatted (NFR-01). */
  amount: string;
  /** Quantity, 4 decimals, verbatim from the API. */
  units: string;
  /** Signed percent, 2 decimals, verbatim from the API. */
  drift_percent: string;
}

export type RebalancingRecommendationStatus = 'pending' | 'accepted' | 'dismissed';

export interface RebalancingRecommendation {
  recommendation_id: string;
  status: RebalancingRecommendationStatus;
  generated_at: string;
  resolved_at: string | null;
  threshold_bps: number;
  proposed_actions: ProposedAction[];
}

export interface ResolveRebalancingResponse {
  recommendation_id: string;
  status: RebalancingRecommendationStatus;
  resolved_at: string;
}

export function getRebalancingRecommendations(): Promise<RebalancingRecommendation[]> {
  return apiRequest<RebalancingRecommendation[]>('/api/rebalancing');
}

export function acceptRebalancingRecommendation(
  recommendationId: string
): Promise<ResolveRebalancingResponse> {
  return apiRequest<ResolveRebalancingResponse>(`/api/rebalancing/${recommendationId}/accept`, {
    method: 'POST',
  });
}

export function dismissRebalancingRecommendation(
  recommendationId: string
): Promise<ResolveRebalancingResponse> {
  return apiRequest<ResolveRebalancingResponse>(`/api/rebalancing/${recommendationId}/dismiss`, {
    method: 'POST',
  });
}
